typedef Vbase64Binary = String; // [RFC 4648](https://datatracker.ietf.org/doc/html/rfc4648) format
typedef Vboolean = bool;
typedef VCanonical = String;
typedef VCode = String;
typedef Vdate = String;
typedef VdateTime = String;
typedef Vdecimal = String;
typedef Vinstant = String;
typedef Vinteger = int;
typedef Vinteger64 = int;
typedef Vmarkdown = String;
typedef Void = String;
typedef VpositiveInt = int;
typedef Vtime = String; // [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals) format
typedef VunsignedInt = int;
typedef Vuri = String; // [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) format
typedef Vurl = String; // [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) format
typedef Vuuid = String;
typedef Vstring = String; // [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986) format
