name: Generate a build and push to another branch

on:
  push:
    branches:
      - main # The branch name your are commit the new changes

jobs:
  pump-version:
    runs-on: ubuntu-latest
    name: Bump Version
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
      new_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - name: git-checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version
        id: bump
        run: |
          # Read current version from pubspec.yaml
          CURRENT_VERSION=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "Current version: $CURRENT_VERSION"
          
          # Extract version parts (assuming format: major.minor.patch+build)
          VERSION_PART=$(echo $CURRENT_VERSION | cut -d '+' -f 1)
          BUILD_PART=$(echo $CURRENT_VERSION | cut -d '+' -f 2)
          
          # Increment build number
          NEW_BUILD=$((BUILD_PART + 1))
          NEW_VERSION="${VERSION_PART}+${NEW_BUILD}"
          
          echo "New version: $NEW_VERSION"
          
          # Update pubspec.yaml
          sed -i "s/^version: .*/version: $NEW_VERSION/" pubspec.yaml
          
          # Set outputs
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "new_tag=v$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pubspec.yaml
          git commit -m "Bump version to ${{ steps.bump.outputs.new_version }}" || echo "No changes to commit"
          git push

  build-web:
    runs-on: ubuntu-latest
    name: Build Web and Push
    needs: pump-version
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build web --wasm --release

      - name: Copy .htaccess
        run: cp .htaccess build/web

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: build/web # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message

  build-android:
    runs-on: ubuntu-latest
    name: Build Android APK and Release
    needs: pump-version
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Get version from pubspec.yaml
        id: version
        run: |
          echo "VERSION=${{ needs.pump-version.outputs.new_version }}" >> $GITHUB_OUTPUT
          echo "TAG=${{ needs.pump-version.outputs.new_tag }}" >> $GITHUB_OUTPUT

      - name: Delete existing release if exists
        run: |
          TAG="${{ steps.version.outputs.TAG }}"
          # Check if release exists and delete it
          if gh release view $TAG >/dev/null 2>&1; then
            echo "Release $TAG exists, deleting..."
            gh release delete $TAG --yes
            # Also delete the tag
            git push --delete origin $TAG || true
          else
            echo "Release $TAG does not exist, proceeding..."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.TAG }}
          name: Release ${{ steps.version.outputs.TAG }}
          body: |
            Release ${{ steps.version.outputs.TAG }}
            
            Changes in this Release:
            - APK build from commit ${{ github.sha }}
          draft: false
          prerelease: false
          files: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive

